# Generated by Django 3.0.8 on 2020-08-18 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0022_auto_20200804_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductErrorAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=256)),
                ('clean', models.CharField(max_length=256)),
                ('error', models.CharField(max_length=256)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('productid', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('errorfield', models.CharField(max_length=256)),
                ('error_description', models.CharField(max_length=256)),
                ('error_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=1, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-error_date'],
            },
        ),
    ]
